services:
  - type: web
    name: mental-health-api
    env: python
    region: singapore  # or change to your nearest region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python flask_api/api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
