services:
  - type: web
    name: mental-health-api
    runtime: python
    region: singapore  # Keep this as your region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_api.api:app  # ✅ Use Gunicorn to start the app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
